USE NH_OP;

SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION dbo.fn_GetKeyDate
(
  @date datetime
)
RETURNS INT
WITH EXECUTE AS CALLER
AS
BEGIN
  RETURN (10000 * YEAR(@date) + 100 * MONTH(@date) + DAY(@date))    
END
GO
