FROM microsoft/dotnet:2-runtime-jessie

# Set the Working Directory
WORKDIR /app

# Configure the listening port to 80
ENV ASPNETCORE_URLS http://*:5001
EXPOSE 5001

# Copy the app
COPY . /app
# Create the mount point to hold volume from host for logs
#VOLUME logs

# Start the app
ENTRYPOINT dotnet src.dll