CREATE TABLE IF NOT EXISTS  Device (  
  DeviceUID varchar(100) NOT NULL,
  ShortRaptorAssetID int(20) unsigned NOT NULL AUTO_INCREMENT, 
  LastActionedUTC datetime(6) DEFAULT NULL,  
  InsertUTC datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdateUTC datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ShortRaptorAssetID),
  UNIQUE KEY UIX_Device_DeviceUID (DeviceUID) 
) ENGINE=InnoDB CHARSET = DEFAULT COLLATE = DEFAULT;
