USE `Alpha-Project-ccss`;

CREATE TABLE IF NOT EXISTS  Device
 (  
  DeviceUID varchar(80) NOT NULL,
  `ShortRaptorProjectID` int(20) unsigned NOT NULL AUTO_INCREMENT,  
  `InsertUTC` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdateUTC` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (ShortRaptorProjectID),
  UNIQUE KEY `UIX_Device_DeviceUID` (DeviceUID) 
) ENGINE=InnoDB CHARSET = DEFAULT COLLATE = DEFAULT;
