namespace VSS.TRex.Designs.Models
{
    public enum DesignProfilerRequestResult
    {
        UnknownError,
        OK,
        CouldNotConnectToServer,
        FailedToConvertClientWGSCoords,
        FailedToLoadDesignFile,
        ProfileGenerationFailure,
        FailedToResultFromResponseVerb,
        UnsupportedDesignType,
        FailedToSaveIntermediaryResult,
        FailedToLoadIntermediaryResult,
        NoElevationsInRequestedPatch,
        ServiceStopped,
        DesignDoesNotSupportSubgridOverlayIndex,
        FailedToSaveSubgridOverlayIndexToStream,
        AlignmentContainsNoElements,
        AlignmentContainsNoStationing,
        AlignmentContainsInvalidStationing,
        InvalidStationValues,
        NoSelectedSiteModel,
        FailedToComputeAlignmentVertices,
        FailedToAddItemToCache,
        FailedToUpdateCache,
        FailedGetDataModelSpatialExtents,
        NoAlignmentsFound,
        InvalidResponseCode,
        DesignDoesNotExist,
        FailedToCalculateBoundary,
        FailedToCalculateAlignmentStationRange
  }
}
