del "..\VSS.TRex\src\gateway\VSS.TRex.Gateway.WebApi\logs\VSS.TRex.Gateway.WebApi.log"
del "..\VSS.TRex\src\netstandard\services\VSS.TRex.Server.Application\bin\Debug\netcoreapp2.0\logs\VSS.TRex.Server.Application.log"
del "..\VSS.TRex\src\netstandard\services\VSS.TRex.Server.DesignElevation\bin\Debug\netcoreapp2.0\logs\VSS.TRex.Server.DesignElevation"
del "..\VSS.TRex\src\netstandard\services\VSS.TRex.Server.MutableData\bin\Debug\netcoreapp2.0\logs\VSS.TRex.Server.MutableData"
del "..\VSS.TRex\src\netstandard\services\VSS.TRex.Server.PSNode\bin\Debug\netcoreapp2.0\logs\VSS.TRex.Server.PSNode"
