FROM microsoft/dotnet:2.1-sdk-alpine as builder

COPY . /build/

WORKDIR /build/AcceptanceTests/scripts
RUN chmod 777 *.sh
RUN ["/bin/sh", "deploy_linux.sh"]

FROM registry.k8s.vspengg.com:80/vss-jenkinsslave:core21

WORKDIR /app
COPY --from=builder /build/AcceptanceTests/deploy .

RUN sed -i 's/\r$//' rm_cr.sh
RUN chmod 775 rm_cr.sh
RUN ["/bin/sh", "rm_cr.sh"]

VOLUME testresults


