FROM microsoft/dotnet:2.0-sdk 

COPY . /build/
WORKDIR /build

RUN dotnet publish ./src/LandfillService.WebApi.netcore/LandfillService.WebApi.netcore.csproj -o /landfillapp --framework netcoreapp2.0 --runtime linux-x64
RUN dotnet publish ./src/LandfillDatasync.netcore/LandfillDatasync.netcore.csproj -o /landfillapp --framework netcoreapp2.0 --runtime linux-x64
