FROM microsoft/dotnet:2.1-sdk-alpine as builder

COPY . /build/
WORKDIR /build

RUN chmod 777 *.sh
#RUN ["/bin/sh", "deploy_linux.sh"]

FROM registry.k8s.vspengg.com:80/vss-jenkinsslave:core21

WORKDIR /app
COPY --from=builder /build/AcceptanceTests .

VOLUME testresults

