using System.Collections.Generic;

namespace VSS.MasterData.Project.WebAPI.Common.Models
{
  /// <summary>
  /// this matches (one hopes) the client list.
  /// </summary>
  public class ProjectTimezone
  {
    // why don't we use this instead (will it work on linux?)
    // var exists = (TimeZoneInfo.GetSystemTimeZones()).Where(x => x.StandardName == tzDisplayNameToSearch).FirstOrDefault();
    // if (exists != null)

    public List<string> timeZone;

    public ProjectTimezone()
    {
      timeZone = new List<string> { "Morocco Standard Time",
                                    "Coordinated Universal Time",
                                    "GMT Standard Time",
                                    "Greenwich Standard Time",
                                    "W. Europe Standard Time",
                                    "Central Europe Standard Time",
                                    "Romance Standard Time",
                                    "Central European Standard Time",
                                    "W. Central Africa Standard Time",
                                    "Namibia Standard Time",
                                    "Jordan Standard Time",
                                    "GTB Standard Time",
                                    "Middle East Standard Time",
                                    "Egypt Standard Time",
                                    "Syria Standard Time",
                                    "E. Europe Standard Time",
                                    "South Africa Standard Time",
                                    "FLE Standard Time",
                                    "Turkey Standard Time",
                                    "Jerusalem Standard Time",
                                    "Russia TZ 1 Standard Time",
                                    "Libya Standard Time",
                                    "Arabic Standard Time",
                                    "Arab Standard Time",
                                    "Belarus Standard Time",
                                    "Russia TZ 2 Standard Time",
                                    "E. Africa Standard Time",
                                    "Iran Standard Time",
                                    "Arabian Standard Time",
                                    "Azerbaijan Standard Time",
                                    "Russia TZ 3 Standard Time",
                                    "Mauritius Standard Time",
                                    "Georgian Standard Time",
                                    "Caucasus Standard Time",
                                    "Afghanistan Standard Time",
                                    "West Asia Standard Time",
                                    "Russia TZ 4 Standard Time",
                                    "Pakistan Standard Time",
                                    "India Standard Time",
                                    "Sri Lanka Standard Time",
                                    "Nepal Standard Time",
                                    "Central Asia Standard Time",
                                    "Bangladesh Standard Time",
                                    "Russia TZ 5 Standard Time",
                                    "Myanmar Standard Time",
                                    "SE Asia Standard Time",
                                    "Russia TZ 6 Standard Time",
                                    "China Standard Time",
                                    "Russia TZ 7 Standard Time",
                                    "Malay Peninsula Standard Time",
                                    "W. Australia Standard Time",
                                    "Taipei Standard Time",
                                    "Ulaanbaatar Standard Time",
                                    "Tokyo Standard Time",
                                    "Korea Standard Time",
                                    "Russia TZ 8 Standard Time",
                                    "Cen. Australia Standard Time",
                                    "AUS Central Standard Time",
                                    "E. Australia Standard Time",
                                    "AUS Eastern Standard Time",
                                    "West Pacific Standard Time",
                                    "Tasmania Standard Time",
                                    "Magadan Standard Time",
                                    "Russia TZ 9 Standard Time",
                                    "Russia TZ 10 Standard Time",
                                    "Central Pacific Standard Time",
                                    "Russia TZ 11 Standard Time",
                                    "New Zealand Standard Time",
                                    "UTC+12",
                                    "Fiji Standard Time",
                                    "Kamchatka Standard Time",
                                    "Tonga Standard Time",
                                    "Samoa Standard Time",
                                    "Line Islands Standard Time",
                                    "Azores Standard Time",
                                    "Cabo Verde Standard Time",
                                    "UTC-02",
                                    "E. South America Standard Time",
                                    "Argentina Standard Time",
                                    "SA Eastern Standard Time",
                                    "Greenland Standard Time",
                                    "Montevideo Standard Time",
                                    "Bahia Standard Time",
                                    "Pacific SA Standard Time",
                                    "Newfoundland Standard Time",
                                    "Paraguay Standard Time",
                                    "Atlantic Standard Time",
                                    "Central Brazilian Standard Time",
                                    "SA Western Standard Time",
                                    "Venezuela Standard Time",
                                    "SA Pacific Standard Time",
                                    "Eastern Standard Time (Mexico)",
                                    "Eastern Standard Time",
                                    "US Eastern Standard Time",
                                    "Central America Standard Time",
                                    "Central Standard Time",
                                    "Central Standard Time (Mexico)",
                                    "Canada Central Standard Time",
                                    "US Mountain Standard Time",
                                    "Mountain Standard Time (Mexico)",
                                    "Mountain Standard Time",
                                    "Pacific Standard Time (Mexico)",
                                    "Pacific Standard Time",
                                    "Alaskan Standard Time",
                                    "Hawaiian Standard Time",
                                    "UTC-11",
                                    "Dateline Standard Time"
      };
    }
  }
}
