using System;
using System.Collections.Generic;
using System.Text;

namespace VSS.TRex.TAGFiles.GridFabric.Responses
{
  /// <summary>
  /// Code if negative means it was generated by mutable SubmitTAGFileExecutor checks. If positive it means its the code from TFA service validation
  /// </summary>
  [Serializable]
  public class SubmitTAGFileResponse
  {
    public string FileName { get; set; }

    public bool Success { get; set; }

    public int Code { get; set; }

    public string Message { get; set; }

    /// <summary>
    /// Default no-arg constructor
    /// </summary>
    public SubmitTAGFileResponse()
    {
    }
  }
}
