del "..\TRex\src\framework\TRexMutableDataServer\bin\Debug\logs\TRexMutableDataServer.log"
del "..\TRex\src\framework\TRexTAGFileSubmittor\bin\Debug\logs\TRexTAGFileSubmittor.log"
del "..\TRex\src\framework\TRexApplicationServer\bin\Debug\logs\TRexApplicationServer.log"
del "..\TRex\src\framework\TRexImmutableDataServer\bin\Debug\logs\TRexImmutableDataServer.log"
del "..\TRex\src\framework\TRexIgniteTest\bin\Debug\logs\TRexIgniteTest.log"
del "..\TRex\src\framework\TRexGridActivator\bin\Debug\logs\TRexGridActivator.log"
del "..\TRex\src\framework\TRexDesignElevationsServer\bin\Debug\logs\TRexDesignElevationsServer.log"
