del "..\TRex\src\gateway\VSS.TRex.Gateway.WebApi\logs\VSS.TRex.Server.Gateway.log"
del "..\TRex\src\gateway\VSS.TRex.Mutable.Gateway.WebApi\logs\VSS.TRex.Mutable.Gateway.WebApi.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.Application\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.Application.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.DesignElevation\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.DesignElevation.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.MutableData\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.MutableData.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.PSNode\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.PSNode.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.Reports\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.Reports.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.QuantizedMesh\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.QuantizedMesh.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.TileRendering\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.TileRenderer.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.TINSurfaceExport\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.ExportTinSurface.log"
del "..\TRex\src\netstandard\services\VSS.TRex.Server.ProjectRebuilder\bin\Debug\netcoreapp3.1\logs\VSS.TRex.Server.ProjectRebuilder.log"

