using System.Collections.Generic;
using VSS.TRex.GridFabric.Requests.Interfaces;
using VSS.TRex.Pipelines;
using VSS.TRex.Profiling.Interfaces;

namespace VSS.TRex.Profiling.GridFabric.Responses
{
  /// <summary>
  /// Contains the set of profile cells generated by a profile analysis executor
  /// </summary>
    public class ProfileRequestResponse : SubGridsPipelinedReponseBase, IAggregateWith<ProfileRequestResponse>
    {
      public List<IProfileCell> ProfileCells;

      /// <summary>
      /// Aggregates an other response with this response
      /// </summary>
      /// <param name="other"></param>
      /// <returns></returns>
      public ProfileRequestResponse AggregateWith(ProfileRequestResponse other)
      {
        ProfileCells.AddRange(other.ProfileCells);

        return this;
      }
    }
}
