using System;
using VSS.VisionLink.Interfaces.Events.MasterData.Interfaces;

namespace VSS.VisionLink.Interfaces.Events.MasterData.Models
{
    /// <summary>
    ///     This event is different to others:
    ///     It is of interest to only ProjectMDM
    ///     Resides in ExtendedModels rather than VSS.VisionLink.Interfaces.Events.MasterData.Models
    ///     Kafka events are generated by ProjecMDM for persistance only.
    ///     There is no consumer to handle these KafkaEvents.
    ///     TCCOrgIDs will be inserted manually into a ProjectMDM database
    ///     This model is here so that
    ///     a) we can use the RepositoryFactory pattern and
    ///     b) we can do Repository tests which reside in the consumer solution
    /// </summary>
    public class CreateCustomerTccOrgEvent : ICustomerEvent
    {
        public string TCCOrgID { get; set; }
        public Guid CustomerUID { get; set; }
        public DateTime ActionUTC { get; set; }
        public DateTime ReceivedUTC { get; set; }
    }
}