using System;
using Repositories.DBModels;
using VSS.VisionLink.Interfaces.Events.MasterData.Interfaces;

namespace VSS.VisionLink.Interfaces.Events.MasterData.Models
{
    /// <summary>
    ///     This event is different to others:
    ///     It is of interest to only ProjectMDM
    ///     Resides in ExtendedModels rather than VSS.VisionLink.Interfaces.Events.MasterData.Models
    ///     Kafka events are generated by ProjecMDM for persistance only.
    ///     There is no consumer to handle these KafkaEvents.
    ///     ProjectMDM will use this repository to insert into it's own database
    ///     This model is here so that
    ///     a) we can use the RepositoryFactory pattern and
    ///     b) we can do Repository tests which reside in the consumer solution
    /// </summary>
    public class CreateImportedFileEvent : IProjectEvent
    {
        public Guid ImportedFileUID { get; set; }
        public Guid CustomerUID { get; set; }
        public ImportedFileType ImportedFileType { get; set; }
        public string Name { get; set; }
        public string FileDescriptor { get; set; }
        public DateTime FileCreatedUtc { get; set; }
        public DateTime FileUpdatedUtc { get; set; }
        public string ImportedBy { get; set; }
        public DateTime? SurveyedUTC { get; set; }
        public Guid ProjectUID { get; set; }
        public DateTime ActionUTC { get; set; }
        public DateTime ReceivedUTC { get; set; }
    }
}