FROM 276986344560.dkr.ecr.us-west-2.amazonaws.com/base-images:dotnet-2.1-sdkas builder

COPY . /build/
WORKDIR /build

RUN chmod 777 *.sh

FROM  276986344560.dkr.ecr.us-west-2.amazonaws.com/base-images:jenkinsslave-core21

WORKDIR /app
COPY --from=builder /build .

VOLUME testresults

