CREATE TABLE IF NOT EXISTS `Machine` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `AssetID` int(10) unsigned NOT NULL,
  `MachineName` varchar(100) NOT NULL,
  `IsJohnDoe` tinyint(1) unsigned NOT NULL,
  `InsertUTC` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UpdateUTC` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`ID`)  COMMENT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;