properties([disableConcurrentBuilds(), pipelineTriggers([])])
/*
node ('master')
{
    stage 'Checkout'
    checkout scm 
dir ("MasterDataConsumers")
{
    def branch = env.BRANCH_NAME
    def buildNumber = env.BUILD_NUMBER
    def versionPrefix = ""
    def suffix = ""
    def branchName = ""
    def openCoverLocation = ""
    def reportGeneratorLocation = ""
    def workspacePath =""
    def openCoverfilters ="-filter:\"+[*]* -[*]*.*Tests -[*]VSS.VisionLink.Interfaces.* -[*]MockClasses.*\"" 


    if (branch.contains("release")) {
       versionPrefix = "1.0."
       branchName = "Release"
       } else if (branch.contains("Dev")) {
       versionPrefix = "0.99."
       branchName = "Dev"
       } else {
       branchName = branch.substring(branch.lastIndexOf("/") + 1)
       suffix = "-" + branchName
       versionPrefix = "0.98."
       }
    
    def versionNumber = versionPrefix + buildNumber
    def fullVersion = versionNumber + suffix

    //openCoverLocation = tool name: 'default OpenCover', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
    openCoverLocation = pwd()
    workspacePath = pwd()
    openCoverLocation = openCoverLocation + "\\tools\\OpenCover.Console.exe"
   //reportGeneratorLocation = tool name: 'default ReportGenerator', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'
    reportGeneratorLocation = pwd()
    reportGeneratorLocation = reportGeneratorLocation + "\\tools\\ReportGenerator.exe"

    stage 'Restore packages'
    bat "dotnet restore"
    stage 'Build solution'
    bat "./build.bat"
    stage 'Run tests and get coverage results'
    bat "del /q ${workspacePath}\\*.xml"
    bat "cd ${workspacePath}\\test\\UnitTests\\MasterDataConsumerTests\\bin\\Debug\\netcoreapp1.0 & \"${openCoverLocation}\" \"-register:user\" -target:\"dotnet-test-mstest.exe\" -targetargs:\"MasterDataConsumerTests.dll\" -output:\"${workspacePath}\\coverageDF.xml\" ${openCoverfilters}"
    bat "cd \"${workspacePath}\" & \"${reportGeneratorLocation}\" \"-reports:${workspacePath}\\*.xml\" \"-reporttypes:Html\" \"-targetdir:${workspacePath}\\Coverage\" "

    def reportDir = "${workspacePath}\\Coverage"
    def reportName = "OpenCover Results"
    publishHTML(target:[allowMissing: true, alwaysLinkToLastBuild: true, keepAll: true, reportDir: reportDir, reportFiles: 'index.htm', reportName: reportName])
}
}
*/
node('Ubuntu_Slave') {

    stage 'Checkout'
    checkout scm 
dir ("MasterDataConsumers")
{
    //Apply version number
    //We will later use it to tag images

    def branch = env.BRANCH_NAME
    def buildNumber = env.BUILD_NUMBER
    def versionPrefix = ""
    def suffix = ""
    def branchName = ""

    if (branch.contains("release")) {
       versionPrefix = "1.0."
       branchName = "release"
       } else if (branch.contains("Dev")) {
       versionPrefix = "0.99."
       branchName = "Dev"
       } else {
       branchName = branch.substring(branch.lastIndexOf("/") + 1)
       suffix = "-" + branchName
       versionPrefix = "0.98."
       }
    
    def versionNumber = versionPrefix + buildNumber
    def fullVersion = versionNumber + suffix
    def workspacePath =""
    currentBuild.displayName = versionNumber + suffix

    stage 'Restore packages'
    sh "dotnet restore --no-cache"
    stage 'Build solution'
    sh "bash ./build.sh"
    stage 'Run unit tests'
    sh "bash ./unittests.sh"
    stage 'Prepare Acceptance tests'
    sh "(cd ./AcceptanceTests/scripts && bash ./deploy_linux.sh)"
    stage 'Compose containers'
    sh "bash ./start_containers.sh"
    stage 'Wait for containers to finish'
    sh "bash ./wait_container.sh testcontainers"
    stage 'Bring containers down and archive the logs'
    sh "(mkdir -p ./logs && docker-compose logs > ./logs/logs.txt)" 
    sh "docker-compose down"

//Here we need to find test results and decide if the build successfull
    stage 'Publish test results and logs'
    currentBuild.result = 'SUCCESS'
    workspacePath = pwd()
    step([$class: 'JUnitResultArchiver', testResults: '**/testresults/*.xml'])
    publishHTML(target:[allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: './logs', reportFiles: 'logs.txt', reportName: 'Build logs'])
 
    if (currentBuild.result=='SUCCESS') {
       //Rebuild Image, tag & push to AWS Docker Repo
       stage 'Build Images'
       stage 'Get ecr login, push image to Repo'
       sh '''eval '$(aws ecr get-login --region us-west-2 --profile vss-grant)' '''

    if (branch.contains("release")) {
       stage 'Build release images'
	   
       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:latest-release-${fullVersion} ./artifacts/MasterDataConsumer"
 

       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest-release-${fullVersion} ./database"

       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest-release-${fullVersion}"
       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:latest-release-${fullVersion}"

       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest-release-${fullVersion}"
       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:latest-release-${fullVersion}"

}
else
{
       stage 'Build development images'

	   
       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:${fullVersion}-${branch} ./artifacts/MasterDataConsumer"
       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:latest ./artifacts/MasterDataConsumer"
 

       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:${fullVersion}-${branch} ./database"
       sh "docker build -t 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest ./database"

       //Publish to AWS Repo
       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:${fullVersion}-${branch}"
       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db"
       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer"
       sh "docker push 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:${fullVersion}-${branch}"

       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:${fullVersion}-${branch}"
       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer-db:latest"
       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:${fullVersion}-${branch}"
       sh "docker rmi -f 276986344560.dkr.ecr.us-west-2.amazonaws.com/vss-masterdataconsumer:latest"
}

    }
}
}