
CREATE TABLE IF NOT EXISTS CustomerTccOrg (  
  CustomerUID varchar(36) NOT NULL,  
  TCCOrgID varchar(50) NOT NULL,
  LastActionedUTC datetime(6) DEFAULT NULL,
  InsertUTC datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UpdateUTC datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (CustomerUID),
  UNIQUE KEY UIX_CustomerTccOrg_CustomerUID (CustomerUID),
  KEY UIX_CustomerTccOrg_TCCOrgID (TCCOrgID)
) ENGINE=InnoDB CHARSET = DEFAULT COLLATE = DEFAULT;
