Feature: CompactionProfile
	I should be able to request Compaction Profile data.

@ignore
Scenario: Compaction Get Slicer Profile
	Given the Compaction Profile service URI "/api/v2/profiles/productiondata/slicer"
  And a projectUid "ff91dd40-1569-4765-a2bc-014321f76ace"
  And a startLatDegrees "36.207310" and a startLonDegrees "-115.019584" and an endLatDegrees "36.207322" And an endLonDegrees "-115.019574"
	When I request a Compaction Profile 
	Then the Compaction Profile should be
"""
{
    "gridDistanceBetweenProfilePoints": 1.6069349832172868,
    "cells": [
        {
            "cellType": 1,
            "station": 0,
            "firstPassHeight": 597.294,
            "highestPassHeight": 597.629,
            "lastPassHeight": 597.367,
            "lowestPassHeight": 597.292,
            "lastCompositeHeight": 597.367,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 272,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.0852058030756496,
            "firstPassHeight": 597.301636,
            "highestPassHeight": 597.603455,
            "lastPassHeight": 597.3687,
            "lowestPassHeight": 597.297058,
            "lastCompositeHeight": 597.3687,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 284,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.10001382506285361,
            "firstPassHeight": 597.303,
            "highestPassHeight": 597.599,
            "lastPassHeight": 597.369,
            "lowestPassHeight": 597.298,
            "lastCompositeHeight": 597.369,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 284,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.11482184705005764,
            "firstPassHeight": 597.302368,
            "highestPassHeight": 597.5917,
            "lastPassHeight": 597.3689,
            "lowestPassHeight": 597.2965,
            "lastCompositeHeight": 597.3689,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 275,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.31995441222371812,
            "firstPassHeight": 597.294,
            "highestPassHeight": 597.49,
            "lastPassHeight": 597.367,
            "lowestPassHeight": 597.276,
            "lastCompositeHeight": 597.367,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 275,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.52508697739737864,
            "firstPassHeight": 597.2947,
            "highestPassHeight": 597.4872,
            "lastPassHeight": 597.364868,
            "lowestPassHeight": 597.2852,
            "lastCompositeHeight": 597.364868,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 263,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.60891033118360127,
            "firstPassHeight": 597.295,
            "highestPassHeight": 597.486,
            "lastPassHeight": 597.364,
            "lowestPassHeight": 597.289,
            "lastCompositeHeight": 597.364,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 263,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.6927336849698239,
            "firstPassHeight": 597.294556,
            "highestPassHeight": 597.488464,
            "lastPassHeight": 597.364441,
            "lowestPassHeight": 597.2878,
            "lastCompositeHeight": 597.364441,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 261,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.81404289635761051,
            "firstPassHeight": 597.294,
            "highestPassHeight": 597.492,
            "lastPassHeight": 597.365,
            "lowestPassHeight": 597.286,
            "lastCompositeHeight": 597.365,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 261,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.93535210774539712,
            "firstPassHeight": 597.29364,
            "highestPassHeight": 597.5072,
            "lastPassHeight": 597.3698,
            "lowestPassHeight": 597.284,
            "lastCompositeHeight": 597.3698,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 269,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.1178068373052017,
            "firstPassHeight": 597.293,
            "highestPassHeight": 597.53,
            "lastPassHeight": 597.377,
            "lowestPassHeight": 597.281,
            "lastCompositeHeight": 597.377,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 269,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 1.3002615668650064,
            "firstPassHeight": 597.294739,
            "highestPassHeight": 597.494446,
            "lastPassHeight": 597.377,
            "lowestPassHeight": 597.2863,
            "lastCompositeHeight": 597.377,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 266,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.3229394024788621,
            "firstPassHeight": 597.295,
            "highestPassHeight": 597.49,
            "lastPassHeight": 597.377,
            "lowestPassHeight": 597.287,
            "lastCompositeHeight": 597.377,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 266,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 1.3456172380927181,
            "firstPassHeight": 597.2948,
            "highestPassHeight": 597.49,
            "lastPassHeight": 597.376953,
            "lowestPassHeight": 597.2865,
            "lastCompositeHeight": 597.376953,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 259,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.6069349832172868,
            "firstPassHeight": 597.293,
            "highestPassHeight": 597.49,
            "lastPassHeight": 597.376,
            "lowestPassHeight": 597.281,
            "lastCompositeHeight": 597.376,
            "designHeight": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 259,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        }
    ],
    "Code": 0,
    "Message": "success"
}
"""
	
