Feature: CompactionProfile
	I should be able to request Compaction Profile data.


Scenario: Compaction Get Slicer Profile
	Given the Compaction Profile service URI "/api/v2/profiles/productiondata/slicer"
  And a projectUid "7925f179-013d-4aaf-aff4-7b9833bb06d6"
  And a startLatDegrees "36.207310" and a startLonDegrees "-115.019584" and an endLatDegrees "36.207322" And an endLonDegrees "-115.019574"
  And a cutfillDesignUid "dd64fe2e-6f27-4a78-82a3-0c0e8a5e84ff"
	When I request a Compaction Profile 
	Then the Compaction Profile should be
"""
{
    "gridDistanceBetweenProfilePoints": 1.6069349835347946,
    "points": [
        {
            "cellType": 1,
            "station": 0,
            "firstPassHeight": 597.353,
            "highestPassHeight": 597.396,
            "lastPassHeight": 597.396,
            "lowestPassHeight": 597.353,
            "lastCompositeHeight": 597.1041,
            "designHeight": 597.438,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 3,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.3338623,
            "cutFillHeight": 597.4387,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.085205803092608473,
            "firstPassHeight": 597.3581,
            "highestPassHeight": 597.388367,
            "lastPassHeight": 597.388367,
            "lowestPassHeight": 597.3581,
            "lastCompositeHeight": 597.1135,
            "designHeight": 597.4414,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.326843262,
            "cutFillHeight": 597.4384,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.10001382414230234,
            "firstPassHeight": 597.359,
            "highestPassHeight": 597.387,
            "lastPassHeight": 597.387,
            "lowestPassHeight": 597.359,
            "lastCompositeHeight": 597.1152,
            "designHeight": 597.442,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.326843262,
            "cutFillHeight": 597.438354,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.11482184519199619,
            "firstPassHeight": 597.36084,
            "highestPassHeight": 597.386963,
            "lastPassHeight": 597.386963,
            "lowestPassHeight": 597.36084,
            "lastCompositeHeight": 597.115234,
            "designHeight": 597.4418,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.3222046,
            "cutFillHeight": 597.4383,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.31995441034733291,
            "firstPassHeight": 597.386,
            "highestPassHeight": 597.386,
            "lastPassHeight": 597.386,
            "lowestPassHeight": 597.386,
            "lastCompositeHeight": 597.1158,
            "designHeight": 597.438,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.3222046,
            "cutFillHeight": 597.4375,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.52508697550266958,
            "firstPassHeight": 597.3832,
            "highestPassHeight": 597.3832,
            "lastPassHeight": 597.3832,
            "lowestPassHeight": 597.3832,
            "lastCompositeHeight": 597.11676,
            "designHeight": 597.435852,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.317810059,
            "cutFillHeight": 597.4367,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.60891033030474173,
            "firstPassHeight": 597.382,
            "highestPassHeight": 597.382,
            "lastPassHeight": 597.382,
            "lowestPassHeight": 597.382,
            "lastCompositeHeight": 597.1172,
            "designHeight": 597.435,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.317810059,
            "cutFillHeight": 597.43634,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.69273368510681388,
            "firstPassHeight": 597.3828,
            "highestPassHeight": 597.3828,
            "lastPassHeight": 597.3828,
            "lowestPassHeight": 597.3828,
            "lastCompositeHeight": 597.1214,
            "designHeight": 597.4362,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.310546875,
            "cutFillHeight": 597.436035,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 0.81404289546017272,
            "firstPassHeight": 597.384,
            "highestPassHeight": 597.384,
            "lastPassHeight": 597.384,
            "lowestPassHeight": 597.384,
            "lastCompositeHeight": 597.127441,
            "designHeight": 597.438,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 1,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.310546875,
            "cutFillHeight": 597.4356,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 0.93535210581353156,
            "firstPassHeight": 597.3836,
            "highestPassHeight": 597.3836,
            "lastPassHeight": 597.376,
            "lowestPassHeight": 597.376,
            "lastCompositeHeight": 597.128,
            "designHeight": 597.4364,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.305175781,
            "cutFillHeight": 597.435364,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.1178068364676852,
            "firstPassHeight": 597.383,
            "highestPassHeight": 597.383,
            "lastPassHeight": 597.364,
            "lowestPassHeight": 597.364,
            "lastCompositeHeight": 597.128845,
            "designHeight": 597.434,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.305175781,
            "cutFillHeight": 597.435059,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 1.3002615671218389,
            "firstPassHeight": 597.383,
            "highestPassHeight": 597.383,
            "lastPassHeight": 597.374634,
            "lowestPassHeight": 597.374634,
            "lastCompositeHeight": 597.138062,
            "designHeight": 597.4385,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.2998047,
            "cutFillHeight": 597.434753,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.3229394016228948,
            "firstPassHeight": 597.383,
            "highestPassHeight": 597.383,
            "lastPassHeight": 597.376,
            "lowestPassHeight": 597.376,
            "lastCompositeHeight": 597.1392,
            "designHeight": 597.439,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.2998047,
            "cutFillHeight": 597.434753,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 0,
            "station": 1.3456172361239505,
            "firstPassHeight": 597.382935,
            "highestPassHeight": 597.382935,
            "lastPassHeight": 597.375549,
            "lowestPassHeight": 597.375549,
            "lastCompositeHeight": 597.139343,
            "designHeight": 597.4387,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.294494629,
            "cutFillHeight": 597.4347,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        },
        {
            "cellType": 1,
            "station": 1.6069349835347946,
            "firstPassHeight": 597.382,
            "highestPassHeight": 597.382,
            "lastPassHeight": 597.371,
            "lowestPassHeight": 597.371,
            "lastCompositeHeight": 597.1405,
            "designHeight": 597.435,
            "cmv": "NaN",
            "cmvPercent": "NaN",
            "cmvHeight": "NaN",
            "mdpPercent": "NaN",
            "mdpHeight": "NaN",
            "temperature": "NaN",
            "temperatureHeight": "NaN",
            "topLayerPassCount": 2,
            "cmvPercentChange": "NaN",
            "speed": 0,
            "speedHeight": 0,
            "cutFill": -0.294494629,
            "cutFillHeight": 597.434265,
            "passCountIndex": 0,
            "temperatureIndex": -1,
            "cmvIndex": -1,
            "mdpIndex": -1,
            "speedIndex": -1
        }
    ],
    "Code": 0,
    "Message": "success"
}
"""
	
